Repository alloy-rs/core, pull requests merged in 2023-07, with the labels that each got.

#166 feature: DynSolType::decode_params
  crates/dyn-abi/src/type.rs
Labels: enhancement

#168 Significant dyn-abi fixes :)
  crates/dyn-abi/src/parser.rs
  crates/dyn-abi/src/token.rs
  crates/dyn-abi/src/type.rs
  crates/dyn-abi/src/value.rs
  crates/sol-types/src/coder/decoder.rs
  crates/sol-types/src/coder/token.rs
  crates/sol-types/src/lib.rs
  crates/sol-types/src/util.rs
Labels: bug, enhancement

#172 fix: remove unwrap in decode_populate
  crates/dyn-abi/src/token.rs
Labels: bug

#174 feat(dyn-abi): clean up and improve performance
  Cargo.toml
  crates/dyn-abi/Cargo.toml
  crates/dyn-abi/src/eip712/coerce.rs
  crates/dyn-abi/src/eip712/mod.rs
  crates/dyn-abi/src/eip712/parser.rs
  crates/dyn-abi/src/eip712/resolver.rs
  crates/dyn-abi/src/eip712/typed_data.rs
  crates/dyn-abi/src/error.rs
  crates/dyn-abi/src/lib.rs
  crates/dyn-abi/src/parser.rs
  crates/dyn-abi/src/token.rs
  crates/dyn-abi/src/type.rs
  crates/dyn-abi/src/value.rs
  crates/primitives/Cargo.toml
  crates/primitives/src/signed/conversions.rs
  crates/sol-types/src/coder/decoder.rs
  crates/sol-types/src/coder/encoder.rs
  crates/sol-types/src/lib.rs
  crates/sol-types/src/types/data_type.rs
  crates/sol-types/src/types/error.rs
  crates/sol-types/src/types/event/topic.rs
  crates/sol-types/src/utils.rs
Labels: enhancement

#181 feat: Solidity type parser
  Cargo.toml
  crates/dyn-abi/Cargo.toml
  crates/dyn-abi/src/arbitrary.rs
  crates/dyn-abi/src/eip712/parser.rs
  crates/dyn-abi/src/eip712/resolver.rs
  crates/dyn-abi/src/eip712/typed_data.rs
  crates/dyn-abi/src/error.rs
  crates/dyn-abi/src/lib.rs
  crates/dyn-abi/src/parser.rs
  crates/dyn-abi/src/resolve.rs
  crates/dyn-abi/src/ty.rs
  crates/json-abi/Cargo.toml
  crates/json-abi/src/internal_type.rs
  crates/json-abi/src/item.rs
  crates/json-abi/src/lib.rs
  crates/json-abi/src/param.rs
  crates/json-abi/src/utils.rs
  crates/json-abi/tests/test.rs
  crates/sol-type-parser/Cargo.toml
  crates/sol-type-parser/README.md
  crates/sol-type-parser/src/error.rs
  crates/sol-type-parser/src/ident.rs
  crates/sol-type-parser/src/lib.rs
  crates/sol-type-parser/src/root.rs
  crates/sol-type-parser/src/stem.rs
  crates/sol-type-parser/src/tuple.rs
  crates/sol-type-parser/src/type_spec.rs
  crates/sol-types/src/coder/token.rs
Labels: enhancement

#183 doc: add parser to readme
  README.md
Labels: documentation

#200 fix: remove unused method body on solstruct
  crates/sol-macro/src/expand/struct.rs
  crates/sol-types/src/types/struct.rs
Labels: bug

#211 docs: add ambiguity details to Encodable rustdoc
  crates/sol-types/src/types/ty.rs
Labels: enhancement

#215 doc: update no-std not in readme
  README.md
Labels: documentation
