Repository alloy-rs/core, pull requests merged in 2024-03, with the labels that each got.

#550 refactor: change identical resolve traits to Specifier<T>
  crates/dyn-abi/benches/types.rs
  crates/dyn-abi/src/eip712/resolver.rs
  crates/dyn-abi/src/ext/abi.rs
  crates/dyn-abi/src/ext/event.rs
  crates/dyn-abi/src/lib.rs
  crates/dyn-abi/src/resolve.rs
  crates/dyn-abi/src/ty.rs
Labels: enhancement

#551 Prestwich/dyn sol error
  crates/dyn-abi/src/arbitrary.rs
  crates/dyn-abi/src/coerce.rs
  crates/dyn-abi/src/dynamic/error.rs
  crates/dyn-abi/src/dynamic/event.rs
  crates/dyn-abi/src/dynamic/mod.rs
  crates/dyn-abi/src/dynamic/token.rs
  crates/dyn-abi/src/dynamic/ty.rs
  crates/dyn-abi/src/dynamic/value.rs
  crates/dyn-abi/src/error.rs
  crates/dyn-abi/src/ext/error.rs
  crates/dyn-abi/src/ext/event.rs
  crates/dyn-abi/src/ext/mod.rs
  crates/dyn-abi/src/lib.rs
  crates/dyn-abi/src/specifier.rs
Labels: enhancement

#553 feat: rlp encoding for logs with generic event data
  crates/primitives/src/log.rs
  crates/sol-macro/src/expand/event.rs
  crates/sol-types/Cargo.toml
  crates/sol-types/src/abi/token.rs
  crates/sol-types/tests/doctests/events.rs
Labels: enhancement

#569 fix: force clippy to stable
  .github/workflows/ci.yml
  crates/dyn-abi/benches/abi.rs
  crates/dyn-abi/benches/types.rs
  crates/json-abi/benches/json_abi.rs
  crates/primitives/benches/primitives.rs
Labels: bug

#578 refactor: break SolInput to its own crate
  Cargo.toml
  crates/sol-macro-input/Cargo.toml
  crates/sol-macro-input/src/attr.rs
  crates/sol-macro-input/src/expander.rs
  crates/sol-macro-input/src/input.rs
  crates/sol-macro-input/src/json.rs
  crates/sol-macro-input/src/lib.rs
  crates/sol-macro/Cargo.toml
  crates/sol-macro/src/expand/contract.rs
  crates/sol-macro/src/expand/enum.rs
  crates/sol-macro/src/expand/error.rs
  crates/sol-macro/src/expand/event.rs
  crates/sol-macro/src/expand/function.rs
  crates/sol-macro/src/expand/mod.rs
  crates/sol-macro/src/expand/struct.rs
  crates/sol-macro/src/expand/udt.rs
  crates/sol-macro/src/lib.rs
Labels: enhancement

#582 small helpers for alloy serde PR
  crates/primitives/src/common.rs
Labels: enhancement

#587 Rearranged type param order so that the Network param is the last
  crates/sol-macro/src/expand/contract.rs
Labels: blocked
